### ISSUE TITLE
Fragment/Activity backstack logic is goofy

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#44]
It can be infinitely added to and doesn't provide particularly useful or useful navigation.

**Comment by CRamsan** [comment]
Is there anything wrong with the "infinite" navigation? What I also want to do is remove the back arrow that appears even when you cannot go back anymore.

**Comment by CRamsan** [comment]
When I came with the design I thought people may want to navigate from Fragment to Fragment and then they would like to navigate back(kinda like a browser navigation).

But I see your point, instead of pushing I could simply replace the current fragment. So if the user presses back they will go back to the menu. That sounds like a good idea.

**Comment by CRamsan** [comment]
I dont think I will work on this any time soon. Closing as wont-fix
